d={1:'a',2:'b',3:'c'}
print(d)
d1 = d.copy()
print(d1)
d1.clear()
print(d1)
print(d.keys())
print(d.values())
print(d.items())
print(d.get(2))
print(d.popitem())
print(d.get(10))
(d.setdefault(11,'z'))
print(d)
d.update({1:'d'})
print(d)
